/**
 * Security Monitor - Frontend Logic
 * Fetches results from results.json and updates the DOM
 */

async function loadResults() {
    const grid = document.getElementById('dashboard-grid');
    const lastUpdateEl = document.getElementById('last-update');

    try {
        // Fetch the JSON file generated by your Python script
        const response = await fetch('results.json');
        
        if (!response.ok) {
            throw new Error('JSON file not found. Ensure the scanner script has run.');
        }

        const data = await response.json();

        // Update the timestamp
        lastUpdateEl.innerText = `Last Scan: ${data.last_update}`;
        
        // Clear the loading state/grid
        grid.innerHTML = '';

        data.sites.forEach(site => {
            // Determine the risk level for the badge
            let statusText = 'Secure';
            let badgeClass = 'bg-green-900/30 text-green-500';
            
            if (site.high > 0) {
                statusText = 'Action Required';
                badgeClass = 'bg-red-900/30 text-red-500';
            } else if (site.medium > 0) {
                statusText = 'Warning';
                badgeClass = 'bg-yellow-900/30 text-yellow-500';
            }

            const card = document.createElement('div');
            card.className = 'card p-6 rounded-xl shadow-xl transition hover:scale-[1.02]';
            
            card.innerHTML = `
                <div class="flex justify-between items-start mb-4">
                    <h2 class="text-xl font-semibold truncate w-2/3" title="${site.url}">${site.url}</h2>
                    <span class="text-xs uppercase font-bold px-2 py-1 rounded ${badgeClass}">
                        ${statusText}
                    </span>
                </div>
                
                <div class="grid grid-cols-3 gap-4 mb-4 text-center">
                    <div class="bg-slate-900/50 p-2 rounded border border-slate-800">
                        <p class="text-red-500 font-bold text-xl">${site.high}</p>
                        <p class="text-xs text-slate-500 uppercase">High</p>
                    </div>
                    <div class="bg-slate-900/50 p-2 rounded border border-slate-800">
                        <p class="text-yellow-500 font-bold text-xl">${site.medium}</p>
                        <p class="text-xs text-slate-500 uppercase">Medium</p>
                    </div>
                    <div class="bg-slate-900/50 p-2 rounded border border-slate-800">
                        <p class="text-blue-500 font-bold text-xl">${site.low}</p>
                        <p class="text-xs text-slate-500 uppercase">Low</p>
                    </div>
                </div>

                <div class="border-t border-slate-700 pt-4 flex justify-between items-center">
                    <p class="text-sm text-slate-400">Total Vulnerabilities</p>
                    <span class="text-white font-mono font-bold text-lg">${site.total_alerts}</span>
                </div>
            `;
            grid.appendChild(card);
        });

    } catch (error) {
        console.error('Error loading results:', error);
        grid.innerHTML = `
            <div class="col-span-full p-8 text-center bg-red-900/20 border border-red-900/50 rounded-lg">
                <p class="text-red-400 font-semibold">Error: ${error.message}</p>
                <p class="text-red-300/60 text-sm mt-2">Check if results.json exists in your repository.</p>
            </div>
        `;
    }
}

// Initial load
document.addEventListener('DOMContentLoaded', loadResults);

// Auto-refresh every 5 minutes
setInterval(loadResults, 300000);
